# Generated by Django 4.0.4 on 2022-04-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_club_event_user_remove_song_album_delete_album_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='e_name',
            new_name='event_name',
        ),
        migrations.RemoveField(
            model_name='club',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='club',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='manager',
        ),
        migrations.AddField(
            model_name='club',
            name='club_head',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
